// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AreDepsInstalled() {
  return window['go']['main']['App']['AreDepsInstalled']();
}

export function GetRoms(arg1) {
  return window['go']['main']['App']['GetRoms'](arg1);
}

export function GetRomsFolder() {
  return window['go']['main']['App']['GetRomsFolder']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InstallDependencies() {
  return window['go']['main']['App']['InstallDependencies']();
}

export function Play(arg1, arg2) {
  return window['go']['main']['App']['Play'](arg1, arg2);
}

export function PollEmulator() {
  return window['go']['main']['App']['PollEmulator']();
}

export function SaveDefaults(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDefaults'](arg1, arg2, arg3);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartUp() {
  return window['go']['main']['App']['StartUp']();
}

export function UpdateContainer() {
  return window['go']['main']['App']['UpdateContainer']();
}
