// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AreDepsInstalled():Promise<boolean>;

export function GetRoms(arg1:string):Promise<Array<string>>;

export function GetRomsFolder():Promise<string>;

export function InstallDependencies():Promise<boolean>;

export function Play(arg1:string,arg2:string):Promise<void>;

export function PollEmulator():Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartUp():Promise<boolean>;

export function UpdateContainer():Promise<void>;
